import 'package:flutter/widgets.dart';

/// Localized Vedic chart labels (signs, planets, house words).
String localizedSign(BuildContext context, String english) {
  final code = Localizations.localeOf(context).languageCode;
  return _signs[code]?[english] ?? _signs['en']![english] ?? english;
}

String localizedPlanet(BuildContext context, String english) {
  final code = Localizations.localeOf(context).languageCode;
  return _planets[code]?[english] ?? _planets['en']![english] ?? english;
}

String localizedPlanetShort(BuildContext context, String english) {
  final code = Localizations.localeOf(context).languageCode;
  return _planetShort[code]?[english] ?? _planetShort['en']![english] ?? english.substring(0, 1);
}

String localizedNakshatra(BuildContext context, String english) {
  if (english.isEmpty) return english;
  final code = Localizations.localeOf(context).languageCode;
  final key = english.trim().replaceAll(RegExp(r'\s+'), ' ');
  if (code == 'hi') return _nakshatraHi[key] ?? key;
  return _nakshatraEn[key] ?? key;
}

const _nakshatraEn = {
  'Ashwini': 'Ashwini',
  'Bharani': 'Bharani',
  'Krittika': 'Krittika',
  'Rohini': 'Rohini',
  'Mrigashira': 'Mrigashira',
  'Ardra': 'Ardra',
  'Punarvasu': 'Punarvasu',
  'Pushya': 'Pushya',
  'Ashlesha': 'Ashlesha',
  'Magha': 'Magha',
  'Purva Phalguni': 'Purva Phalguni',
  'Uttara Phalguni': 'Uttara Phalguni',
  'Hasta': 'Hasta',
  'Chitra': 'Chitra',
  'Swati': 'Swati',
  'Vishakha': 'Vishakha',
  'Anuradha': 'Anuradha',
  'Jyeshtha': 'Jyeshtha',
  'Mula': 'Mula',
  'Purva Ashadha': 'Purva Ashadha',
  'Uttara Ashadha': 'Uttara Ashadha',
  'Shravana': 'Shravana',
  'Dhanishta': 'Dhanishta',
  'Shatabhisha': 'Shatabhisha',
  'Purva Bhadrapada': 'Purva Bhadrapada',
  'Uttara Bhadrapada': 'Uttara Bhadrapada',
  'Revati': 'Revati',
};

const _nakshatraHi = {
  'Ashwini': 'अश्विनी',
  'Bharani': 'भरणी',
  'Krittika': 'कृत्तिका',
  'Rohini': 'रोहिणी',
  'Mrigashira': 'मृगशिरा',
  'Ardra': 'आर्द्रा',
  'Punarvasu': 'पुनर्वसु',
  'Pushya': 'पुष्य',
  'Ashlesha': 'आश्लेषा',
  'Magha': 'मघा',
  'Purva Phalguni': 'पूर्व फाल्गुनी',
  'Uttara Phalguni': 'उत्तर फाल्गुनी',
  'Hasta': 'हस्त',
  'Chitra': 'चित्रा',
  'Swati': 'स्वाती',
  'Vishakha': 'विशाखा',
  'Anuradha': 'अनुराधा',
  'Jyeshtha': 'ज्येष्ठा',
  'Mula': 'मूल',
  'Purva Ashadha': 'पूर्वाषाढ़ा',
  'Uttara Ashadha': 'उत्तराषाढ़ा',
  'Shravana': 'श्रवण',
  'Dhanishta': 'धनिष्ठा',
  'Shatabhisha': 'शतभिषा',
  'Purva Bhadrapada': 'पूर्व भाद्रपद',
  'Uttara Bhadrapada': 'उत्तर भाद्रपद',
  'Revati': 'रेवती',
};

const _signs = {
  'en': {
    'Aries': 'Aries',
    'Taurus': 'Taurus',
    'Gemini': 'Gemini',
    'Cancer': 'Cancer',
    'Leo': 'Leo',
    'Virgo': 'Virgo',
    'Libra': 'Libra',
    'Scorpio': 'Scorpio',
    'Sagittarius': 'Sagittarius',
    'Capricorn': 'Capricorn',
    'Aquarius': 'Aquarius',
    'Pisces': 'Pisces',
  },
  'hi': {
    'Aries': 'मेष',
    'Taurus': 'वृष',
    'Gemini': 'मिथुन',
    'Cancer': 'कर्क',
    'Leo': 'सिंह',
    'Virgo': 'कन्या',
    'Libra': 'तुला',
    'Scorpio': 'वृश्चिक',
    'Sagittarius': 'धनु',
    'Capricorn': 'मकर',
    'Aquarius': 'कुम्भ',
    'Pisces': 'मीन',
  },
  'de': {
    'Aries': 'Widder',
    'Taurus': 'Stier',
    'Gemini': 'Zwillinge',
    'Cancer': 'Krebs',
    'Leo': 'Löwe',
    'Virgo': 'Jungfrau',
    'Libra': 'Waage',
    'Scorpio': 'Skorpion',
    'Sagittarius': 'Schütze',
    'Capricorn': 'Steinbock',
    'Aquarius': 'Wassermann',
    'Pisces': 'Fische',
  },
  'es': {
    'Aries': 'Aries',
    'Taurus': 'Tauro',
    'Gemini': 'Géminis',
    'Cancer': 'Cáncer',
    'Leo': 'Leo',
    'Virgo': 'Virgo',
    'Libra': 'Libra',
    'Scorpio': 'Escorpio',
    'Sagittarius': 'Sagitario',
    'Capricorn': 'Capricornio',
    'Aquarius': 'Acuario',
    'Pisces': 'Piscis',
  },
  'fr': {
    'Aries': 'Bélier',
    'Taurus': 'Taureau',
    'Gemini': 'Gémeaux',
    'Cancer': 'Cancer',
    'Leo': 'Lion',
    'Virgo': 'Vierge',
    'Libra': 'Balance',
    'Scorpio': 'Scorpion',
    'Sagittarius': 'Sagittaire',
    'Capricorn': 'Capricorne',
    'Aquarius': 'Verseau',
    'Pisces': 'Poissons',
  },
  'el': {
    'Aries': 'Κριός',
    'Taurus': 'Ταύρος',
    'Gemini': 'Δίδυμοι',
    'Cancer': 'Καρκίνος',
    'Leo': 'Λέων',
    'Virgo': 'Παρθένος',
    'Libra': 'Ζυγός',
    'Scorpio': 'Σκορπιός',
    'Sagittarius': 'Τοξότης',
    'Capricorn': 'Αιγόκερως',
    'Aquarius': 'Υδροχόος',
    'Pisces': 'Ιχθύες',
  },
  'nl': {
    'Aries': 'Ram',
    'Taurus': 'Stier',
    'Gemini': 'Tweelingen',
    'Cancer': 'Kreeft',
    'Leo': 'Leeuw',
    'Virgo': 'Maagd',
    'Libra': 'Weegschaal',
    'Scorpio': 'Schorpioen',
    'Sagittarius': 'Boogschutter',
    'Capricorn': 'Steenbok',
    'Aquarius': 'Waterman',
    'Pisces': 'Vissen',
  },
};

const _planets = {
  'en': {
    'Sun': 'Sun',
    'Moon': 'Moon',
    'Mars': 'Mars',
    'Mercury': 'Mercury',
    'Venus': 'Venus',
    'Jupiter': 'Jupiter',
    'Saturn': 'Saturn',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
  'hi': {
    'Sun': 'सूर्य',
    'Moon': 'चंद्र',
    'Mars': 'मंगल',
    'Mercury': 'बुध',
    'Venus': 'शुक्र',
    'Jupiter': 'गुरु',
    'Saturn': 'शनि',
    'Rahu': 'राहु',
    'Ketu': 'केतु',
    'Lagna': 'लग्न',
  },
  'de': {
    'Sun': 'Sonne',
    'Moon': 'Mond',
    'Mars': 'Mars',
    'Mercury': 'Merkur',
    'Venus': 'Venus',
    'Jupiter': 'Jupiter',
    'Saturn': 'Saturn',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
  'es': {
    'Sun': 'Sol',
    'Moon': 'Luna',
    'Mars': 'Marte',
    'Mercury': 'Mercurio',
    'Venus': 'Venus',
    'Jupiter': 'Júpiter',
    'Saturn': 'Saturno',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
  'fr': {
    'Sun': 'Soleil',
    'Moon': 'Lune',
    'Mars': 'Mars',
    'Mercury': 'Mercure',
    'Venus': 'Vénus',
    'Jupiter': 'Jupiter',
    'Saturn': 'Saturne',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
  'el': {
    'Sun': 'Ήλιος',
    'Moon': 'Σελήνη',
    'Mars': 'Άρης',
    'Mercury': 'Ερμής',
    'Venus': 'Αφροδίτη',
    'Jupiter': 'Δίας',
    'Saturn': 'Κρόνος',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
  'nl': {
    'Sun': 'Zon',
    'Moon': 'Maan',
    'Mars': 'Mars',
    'Mercury': 'Mercurius',
    'Venus': 'Venus',
    'Jupiter': 'Jupiter',
    'Saturn': 'Saturnus',
    'Rahu': 'Rahu',
    'Ketu': 'Ketu',
    'Lagna': 'Lagna',
  },
};

const _planetShort = {
  'en': {
    'Sun': 'Su',
    'Moon': 'Mo',
    'Mars': 'Ma',
    'Mercury': 'Me',
    'Venus': 'Ve',
    'Jupiter': 'Ju',
    'Saturn': 'Sa',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
  'hi': {
    'Sun': 'सू',
    'Moon': 'च',
    'Mars': 'मं',
    'Mercury': 'बु',
    'Venus': 'शु',
    'Jupiter': 'गु',
    'Saturn': 'श',
    'Rahu': 'रा',
    'Ketu': 'के',
  },
  'de': {
    'Sun': 'So',
    'Moon': 'Mo',
    'Mars': 'Ma',
    'Mercury': 'Me',
    'Venus': 'Ve',
    'Jupiter': 'Ju',
    'Saturn': 'Sa',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
  'es': {
    'Sun': 'Sol',
    'Moon': 'Lu',
    'Mars': 'Mar',
    'Mercury': 'Mer',
    'Venus': 'Ven',
    'Jupiter': 'Júp',
    'Saturn': 'Sat',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
  'fr': {
    'Sun': 'Sol',
    'Moon': 'Lun',
    'Mars': 'Mar',
    'Mercury': 'Mer',
    'Venus': 'Vén',
    'Jupiter': 'Jup',
    'Saturn': 'Sat',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
  'el': {
    'Sun': 'Ήλ',
    'Moon': 'Σε',
    'Mars': 'Άρ',
    'Mercury': 'Ερ',
    'Venus': 'Αφ',
    'Jupiter': 'Δί',
    'Saturn': 'Κρ',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
  'nl': {
    'Sun': 'Zo',
    'Moon': 'Ma',
    'Mars': 'Ma',
    'Mercury': 'Me',
    'Venus': 'Ve',
    'Jupiter': 'Ju',
    'Saturn': 'Sa',
    'Rahu': 'Ra',
    'Ketu': 'Ke',
  },
};
